# Generated by Django 5.1.7 on 2025-04-27 16:40

import django.db.models.deletion
import routes.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_point', routes.fields.WKTGeometryField()),
                ('destination', routes.fields.WKTGeometryField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('version', models.PositiveIntegerField(default=0)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_routes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('location', routes.fields.WKTGeometryField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['share_token'], name='routes_rout_share_t_d161df_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_shared'], name='routes_rout_is_shar_04bdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['version'], name='routes_rout_version_2101b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waypoint',
            unique_together={('route', 'order')},
        ),
    ]
